### ISSUE TITLE
linux version gets a core dump segment fault

### ISSUE THREAD

**Issue by OnikenX** [lolamtisch/Discord-RPC-Extension#13]

**Comment by lolamtisch** [comment]
What PC architecture have you? sure it is 64bit? did you try both versions?
The program was never tested on linux so it very possible that it does not work.

What should work always is running the Programm directly in nodejs. It is described in the end of the release page. https://github.com/lolamtisch/Discord-RPC-Extension/releases

If you need more help or have smaller questions. You can always find us on discord.
https://discordapp.com/invite/cTH4yaw

Btw If you have the know how you could try to fix it and open a pull request :wink:

**Comment by OnikenX** [comment]
sorry for the little information and being this late,im running in a 64bit archlinux installation;
npm install says that the dependecies have vulnerablities, and i dont know how to ignore the warnings;
I only have C/C++ knowledge, i dont know how to work with node and have little knowledge of javascript;
if there is a way to help i would like too, if you have some guides to learn how to work with node that can help me help this project i would gladly try to learn

**Comment by lolamtisch** [comment]
@OnikenX 
👍 Nice to hear.

Lets continue on discord. It makes it easier to communicate. First we will need to get npm install running on your system.
https://discordapp.com/invite/cTH4yaw

**Comment by tcarrio** [comment]
I'm hoping to investigate this myself further in the near future. Would be good to get this set up and confirmed functionality. The release binary worked on its own, though I couldn't get an update through with the extension I had already installed (StadiaRPC). I'll have more time to check in the future. I joined the Discord for further discussion of this as well. Ping me at `scensorECHO` if you need me.

**Comment by OnikenX** [comment]
No need @tcarrio , it is working now, don't know why but the tray one is working for me.
