### ISSUE TITLE
Antivirus detected a virus in RPC

### ISSUE THREAD

**Issue by Rediowz** [lolamtisch/Discord-RPC-Extension#15]
Is it a false positive ? The file was named Hacktool something something

**Comment by Rediowz** [comment]
HackTool.Win32.LaZagne.dm is the name

**Comment by lolamtisch** [comment]
It should be a false positive.
You could try the no tray version, because i think that is what is making problems with the antivirus.

**Comment by henrik9999** [comment]
should be fine now
