### ISSUE TITLE
Party invites support?

### ISSUE THREAD

**Issue by soap-less** [lolamtisch/Discord-RPC-Extension#16]
This might be super hard to do, but I was curious if there was any chance for the API to support the group invite feature(where you can hit the + and invite people)? Thanks.
![image](https://user-images.githubusercontent.com/9097594/70967307-c865b980-204a-11ea-837d-724e31581387.png)

**Comment by lolamtisch** [comment]
I am going to take a look if it is even possible or makes sense. The documentation is very vague in that aspect. Not sure if the Application has to be verified by discord or not. I will need to implement to test.

**Comment by lolamtisch** [comment]
Oh forgot to close the issue. This is supported already as you know
