### ISSUE TITLE
macOS w/ no SysTray "damaged"

### ISSUE THREAD

**Issue by mapuya19** [lolamtisch/Discord-RPC-Extension#24]
When attempting to open, the following pops up:

<img width="532" alt="ScreenShot" src="https://user-images.githubusercontent.com/15944396/89162789-2d1e4780-d53a-11ea-859d-bb3e5114ac9b.png">

**Comment by henrik9999** [comment]
I think you have to run it through the console

**Comment by mapuya19** [comment]
> I think you have to run it through the console

Thanks! Not sure why I didn't think of that.
