### ISSUE TITLE
Improve Mac desktop app

### ISSUE THREAD

**Issue by FayneAldan** [lolamtisch/Discord-RPC-Extension#30]
The icon on the menu bar takes up WAY too much space: 
![image](https://user-images.githubusercontent.com/1149870/107118055-b5f4a380-683b-11eb-9b3c-ee3b3d389d36.png)

It would also be nice if the desktop app could run standalone so that the Terminal doesn't have to be kept open for the app to work. Would also be nice if it could be set to run at startup.

**Comment by lolamtisch** [comment]
I have no mac. So i cant test it. Either way i am not very happy with the current implementation of the Server. When i have some time, which i wont have for a long time I will look into alternatives.

The debugging version of the application is the same as the normal version just without the tray. So you could just use that.
To the startup thing, not sure how it works on mac but there should be some way to do that and suppresing the terminal too. Atleast on linux/windows it is easy.

**Comment by mm12** [comment]
Hi, one thing I think should be implemented: Either remove the text that says "Discord Rich Presence" or at least shorten it to "DRP". it just takes up a ton or space. 

> The icon on the menu bar takes up WAY too much space:
> ![image](https://user-images.githubusercontent.com/1149870/107118055-b5f4a380-683b-11eb-9b3c-ee3b3d389d36.png)
> 
> It would also be nice if the desktop app could run standalone so that the Terminal doesn't have to be kept open for the app to work. Would also be nice if it could be set to run at startup.

To run it at startup, i believe you can go to `System Preferences > Users & Groups > Your Profile` and at the top select `login items`, Press the "+" and add the executable.

**Comment by FayneAldan** [comment]
> To run it at startup, i believe you can go to `System Preferences > Users & Groups > Your Profile` and at the top select `login items`, Press the "+" and add the executable.

Ah. I just got my Mac so I didn't know I could do that. Maybe that could be included in the install instructions.

**Comment by mm12** [comment]
> > To run it at startup, i believe you can go to `System Preferences > Users & Groups > Your Profile` and at the top select `login items`, Press the "+" and add the executable.
> 
> Ah. I just got my Mac so I didn't know I could do that. Maybe that could be included in the install instructions.

Yeah, I got mine as a gift about 5-6 years ago for school stuff (though it was locked down until about a year ago) and don't have money to buy a better computer, so I know this thing pretty well

**Comment by FayneAldan** [comment]
I found out how to run the program without the terminal. You use `nohup`. I made this `.sh` program to run the program in the background:

```sh
#!/bin/sh

cd "`dirname "$0"`"
nohup ./server_macos_debug &
```
The `cd` is necessary as apparently when you run an sh program, the default directory is `~`

**Comment by Notarin** [comment]
if this is solved, can OP or devs close it?

**Comment by akavi1** [comment]
@FayneAldan how did you get it to run without terminal? I can't figure out how to make it executable. chmod +x doesn't do anything

**Comment by akavi1** [comment]
> @FayneAldan how did you get it to run without terminal? I can't figure out how to make it executable. chmod +x doesn't do anything

Figured it out. Here's the solution in case anyone else runs into the same problem.
https://stackoverflow.com/questions/8409946/how-do-i-make-this-file-sh-executable-via-double-click
