### ISSUE TITLE
On/Off Toggle

### ISSUE THREAD

**Issue by Notarin** [lolamtisch/Discord-RPC-Extension#33]
an on/off toggle would be much appreciated, rather than having to kill and reopen the extension

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/110816785-f0fb5400-828b-11eb-89da-5ba4d190b50c.png)
That is an on off button

**Comment by Notarin** [comment]
Thank you, I was not aware. Closing, Feature already implemented.

**Comment by Natron4** [comment]
Does this feature still work?  My status doesn't clear when clicking it
