### ISSUE TITLE
Service worker navigation preload requests cancelled

### ISSUE THREAD

**Issue by ChristopherKlay** [lolamtisch/Discord-RPC-Extension#37]
Currently working on supporting the Discord presence system via Stadia Enhanced and the presence shows up perfectly fine, but i do get errors reported;

> The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

This happens in both situations; Registering at the start and updating over time and registering when needed (i.e. a game starts) while updating during the games session only.

Also; Is there any way to contact you via i.e. Discord? I'd love to talk about Discords presence system in general and future changes / possibilities in terms of projects. Angenehmen Start in die Woche (:

**Comment by lolamtisch** [comment]
Are you sure the errors are from the extension, because i am not sure what they mean atm.
 Here my discord server. See you there
https://discord.gg/cTH4yaw
