### ISSUE TITLE
Configuration for the installable server

### ISSUE THREAD

**Issue by Notarin** [lolamtisch/Discord-RPC-Extension#41]
While the extension itself is presentable and feels nice, the server counterpart just feels incomplete.
it would be incredible if more configuration and options were available in the server, like a server-side pause, keep-alive options, perhaps picking a source in the event of multiple browsers, etc.
I feel like the server is greatly lacking useful features to compliment the extension.

**Comment by Notarin** [comment]
#40 Take this for example, this could be a feature to add, while it in itself isn't worth the effort, i believe that when paired with more options and somewhat an overhaul, it definitely adds to the experience and makes the time and effort worth the return.

**Comment by lolamtisch** [comment]
The server programm is only a proxy. It nearly has no logic. So it is probably the worse place to put anything. On top that not every platform has a System tray, making it difficult to change options.

The extension contains all the logic. So the config would need to be done there.

**Comment by Notarin** [comment]
While i understand what you mean, even a proxy deserves some configuration and options, yes it has nearly no logic, but i still believe that it can have more options than 'exit'.
also, you're correct that not all platforms have a systray, im not sure what to think about that.
If you dont plan on implementing this, can you tag this issue as 'will not implement'?
