### ISSUE TITLE
the rpc doesnt work sometimes 

### ISSUE THREAD

**Issue by ChrisAust1n** [lolamtisch/Discord-RPC-Extension#42]
after sometime if i change websites the status freezes or doesnt show anything even if i restart the app and the extention is their any fix for this?

**Comment by lolamtisch** [comment]
Discord sometimes freezes. Restarting the discord client (cntr + r) fixes it normally.

**Comment by ChrisAust1n** [comment]
but sometimes the rpc doesnt even start showing the status at startup and i have it start on startup

**Comment by lolamtisch** [comment]
What page are you using it on? Could be a problem with that specific presence

**Comment by ChrisAust1n** [comment]
ye i got it in some pages pre wrap needs perm after sometime idk why but thanks for the help you can close the issue Thank you again
