### ISSUE TITLE
No active presence even thought youtube presence is on (PreWrap)

### ISSUE THREAD

**Issue by JonasBBX** [lolamtisch/Discord-RPC-Extension#43]
Starting 0.1.2
WebSocket created
Connected
Recived { action: 'disconnect' }
Could not disconnect. Because not connected.
Recived { action: 'disconnect' }
Could not disconnect. Because not connected.

**Comment by Gilgamesh0028** [comment]
This is still happening. I have done as you said, and done a full-restart. Pre-Wrap, is active and running, as well as server_win.exe, taken from the latest release. (running with admin).
![image](https://user-images.githubusercontent.com/98428877/164152644-b6a0b11f-5308-4f52-b4ed-ba2d3b376fc6.png)

Perhaps this has something to do with my usage of ProtonVPN?

**Comment by lolamtisch** [comment]
![image](https://user-images.githubusercontent.com/12599334/164211880-e5098bf1-ed2a-43d8-8d0f-dd9fc336b4e9.png)
What does the extension popup say?

**Comment by Gilgamesh0028** [comment]
The Extension has no popup.
I already reinstalled it, from the firefox extension hub (addons.mozilla.org
).
I think the logs would say more, however I am unsure of where they are
located.

**Comment by lolamtisch** [comment]
It has to have a popup. You are sure you have 
https://addons.mozilla.org/de/firefox/addon/discord-rich-presence/ installed?

**Comment by Gilgamesh0028** [comment]
Yep, I have that extension installed.
Are there logs anywhere I can upload for you to review?

**Comment by lolamtisch** [comment]
Could you join our discord? It is easier to debug like that.
https://discord.com/invite/cTH4yaw
