### ISSUE TITLE
[SUGGESTION] Change from "Playing" to "Watching"

### ISSUE THREAD

**Issue by zero5enpai** [lolamtisch/Discord-RPC-Extension#57]
Changing the state to "Watching [...]" 
![image](https://user-images.githubusercontent.com/40106969/226779314-a686695f-9a30-4e95-97e7-c42984b3ae29.png)
is way more fitting then "Playing [...]" 
![image](https://user-images.githubusercontent.com/40106969/226779113-6f59fde6-6abd-45a0-996b-17a9f0b7bd0a.png)

**Comment by zero5enpai** [comment]
I did dig through the code but wasnt able to find any state options...

**Comment by lolamtisch** [comment]
Discord does not allow that
