### ISSUE TITLE
Wanting to change "Playing" status to "Watching"

### ISSUE THREAD

**Issue by Natron4** [lolamtisch/Discord-RPC-Extension#62]
Hi hi.  This isn't an issue per se, it's more of a question I have.  I'm not sure if it's possible, but I think it'd be nice to display 'Watching' on the rich presence instead of 'Playing'.  I've found some examples of code that would allow that, but I'm not sure if I'm able to edit your code, nor where to start.  If you could offer some guidance I'd greatly appreciate it :)

**Comment by henrik9999** [comment]
#46 #57 

It's not possible to set the status to watching without turning your account into a self bot which is against discord tos

**Comment by Natron4** [comment]
Okay thank you!  I really hope they make it easier to update it in the future haha
