### ISSUE TITLE
Possible Customization 

### ISSUE THREAD

**Issue by Natron4** [lolamtisch/Discord-RPC-Extension#63]
Hi hi

Is it possible to display the anime title next to **Playing** rather than just "Anime"? I also wanted to know if removing the View Anime button on the bottom is possible.  If this would require you re-editing the code, don't worry about it, I'm more-so just curious about changing it myself

Hypothetically I've thought about using a custom Vencord plugin to override the existing application.  What are your thoughts?

**Comment by lolamtisch** [comment]
This is more of a malsync issue. 

But it is not possible to add the anime name. We would need to create a seperate application in discord for that. That is just not feasable. With the next release we at least can switch to `watching anime` instead of `playing anime`
