### ISSUE TITLE
[FEAT] Allow extensions to specify the activity type

### ISSUE THREAD

**Issue by Kyrela** [lolamtisch/Discord-RPC-Extension#67]
Allow extensions to specify the activity type via the API, e.g. "Watching" or "Competing in", as specified on docs: [Activity Structure](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-structure) and [Activity Types](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types)

**Comment by lolamtisch** [comment]
With the newest version of the extension they are now supported [Playing, Listening, Watching, Competing]

**Comment by Kyrela** [comment]
Thanks!
